---
- name: sysconfig
  hosts: app
  become: true
  gather_facts: no
  tasks:
    - name: create admin user
      user: 
        name: admin 
        state: present
        uid: 5005
      tags:
        - user
    - name: remove dojo user
      user: 
        name: dojo 
        state: absent
    - name: install tree
      yum: 
        name: tree 
        state: present
